groups:
- name: audit_service_alerts
  rules:
  # Alertas de disponibilidade do serviço - crítico para conformidade regulatória
  - alert: AuditServiceDown
    expr: up{job="iam-audit-service"} == 0
    for: 1m
    labels:
      severity: critical
      tier: core
      service: iam-audit
      category: availability
    annotations:
      summary: "Serviço de auditoria indisponível"
      description: "Serviço de auditoria está inoperante por mais de 1 minuto. Isso compromete o registro e rastreabilidade de eventos críticos."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/service-down"
      dashboard: "https://grafana.innovabiz.com/d/iam-audit-overview"

  # Alertas de performance - impactam SLAs de processamento de eventos de auditoria
  - alert: AuditHighLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="iam-audit-service"}[5m])) by (le, path)) > 0.5
    for: 5m
    labels:
      severity: warning
      tier: core
      service: iam-audit
      category: performance
    annotations:
      summary: "Alta latência no processamento de eventos"
      description: "O serviço de auditoria está apresentando latência elevada (P95 > 500ms) nos últimos 5 minutos."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/high-latency"

  # Alertas de erro - críticos para conformidade com LGPD, GDPR e regulamentações financeiras
  - alert: AuditHighErrorRate
    expr: sum(rate(http_requests_total{job="iam-audit-service", status_code=~"5.."}[5m])) / sum(rate(http_requests_total{job="iam-audit-service"}[5m])) > 0.05
    for: 5m
    labels:
      severity: critical
      tier: core
      service: iam-audit
      category: errors
      compliance_impact: true
    annotations:
      summary: "Taxa elevada de erros no serviço de auditoria"
      description: "Mais de 5% das requisições estão resultando em erros 5xx nos últimos 5 minutos."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/high-error-rate"

  # Alertas de retenção - monitoram a saúde das políticas de retenção (compliance)
  - alert: AuditRetentionPolicyFailure
    expr: sum(increase(audit_retention_policy_failure[1h])) > 0
    for: 10m
    labels:
      severity: critical
      tier: core
      service: iam-audit
      category: compliance
      compliance_impact: true
    annotations:
      summary: "Falhas na execução de políticas de retenção"
      description: "Detectadas falhas na execução de políticas de retenção de eventos de auditoria, impactando a conformidade com LGPD, GDPR e outras regulamentações."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/retention-failures"  # Alertas de conformidade regional - específicos por regulamentação e região
  - alert: AuditComplianceFailure
    expr: audit_regional_compliance_status{framework=~"LGPD|GDPR|PCI-DSS|SOX"} == 0
    for: 5m
    labels:
      severity: critical
      tier: compliance
      service: iam-audit
      category: compliance
      compliance_impact: true
    annotations:
      summary: "Falha de conformidade detectada"
      description: "Status de conformidade com {{ $labels.framework }} na região {{ $labels.regional_context }} para o tenant {{ $labels.tenant_id }} está em estado não conforme."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/compliance-failures"

  # Monitoramento de componentes críticos - banco de dados, cache, fila
  - alert: AuditDatabaseUnhealthy
    expr: audit_service_health_status{component="database"} == 0
    for: 2m
    labels:
      severity: critical
      tier: data
      service: iam-audit
      category: health
    annotations:
      summary: "Banco de dados do serviço de auditoria indisponível"
      description: "O componente de banco de dados do serviço de auditoria está reportando status não saudável."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/database-issues"

  - alert: AuditCacheUnhealthy
    expr: audit_service_health_status{component="redis_cache"} == 0
    for: 2m
    labels:
      severity: warning
      tier: cache
      service: iam-audit
      category: health
    annotations:
      summary: "Cache Redis do serviço de auditoria indisponível"
      description: "O componente de cache do serviço de auditoria está reportando status não saudável."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/cache-issues"

  # Alertas específicos de multi-tenant - identificam problemas por tenant
  - alert: AuditHighTenantErrorRate
    expr: sum by (tenant_id) (rate(http_requests_total{job="iam-audit-service", status_code=~"5.."}[5m])) / sum by (tenant_id) (rate(http_requests_total{job="iam-audit-service"}[5m])) > 0.1
    for: 5m
    labels:
      severity: warning
      tier: tenant
      service: iam-audit
      category: errors
    annotations:
      summary: "Alta taxa de erros para tenant específico"
      description: "O tenant {{ $labels.tenant_id }} está experimentando uma taxa de erros superior a 10% nos últimos 5 minutos."
      dashboard: "https://grafana.innovabiz.com/d/iam-audit-tenant/{{ $labels.tenant_id }}"

  # Alertas para saturação e carga do sistema
  - alert: AuditHighLoad
    expr: sum(rate(http_requests_total{job="iam-audit-service"}[1m])) > 1000
    for: 5m
    labels:
      severity: warning
      tier: core
      service: iam-audit
      category: saturation
    annotations:
      summary: "Carga elevada no serviço de auditoria"
      description: "O serviço de auditoria está processando mais de 1000 requisições por minuto nos últimos 5 minutos, o que pode causar degradação de performance."
      runbook_url: "https://internal-docs.innovabiz.com/iam/audit/runbooks/high-load"