# IAM - Serviço para ambiente de Produção
# Este manifesto define o serviço Kubernetes para o IAM em ambiente de Produção
apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: innovabiz-iam-production
  labels:
    app: iam-service
    module: iam
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: iam-service