apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webauthn.fullname" . }}-config
  labels:
    {{- include "webauthn.labels" . | nindent 4 }}
data:
  # Application Configuration
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  
  # WebAuthn Configuration
  WEBAUTHN_RP_NAME: {{ .Values.env.WEBAUTHN_RP_NAME | quote }}
  WEBAUTHN_RP_ID: {{ .Values.env.WEBAUTHN_RP_ID | quote }}
  WEBAUTHN_ORIGIN: {{ .Values.env.WEBAUTHN_ORIGIN | quote }}
  WEBAUTHN_TIMEOUT: {{ .Values.env.WEBAUTHN_TIMEOUT | quote }}
  
  # Security Configuration
  JWT_ALGORITHM: {{ .Values.env.JWT_ALGORITHM | quote }}
  RATE_LIMIT_WINDOW: {{ .Values.env.RATE_LIMIT_WINDOW | quote }}
  RATE_LIMIT_MAX: {{ .Values.env.RATE_LIMIT_MAX | quote }}
  
  # Monitoring Configuration
  METRICS_ENABLED: {{ .Values.env.METRICS_ENABLED | quote }}
  TRACING_ENABLED: {{ .Values.env.TRACING_ENABLED | quote }}
  
  # Application Config JSON
  {{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}