apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webauthn.fullname" . }}-secrets
  labels:
    {{- include "webauthn.labels" . | nindent 4 }}
type: Opaque
data:
  # Database Configuration
  {{- if .Values.secrets.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc }}
  {{- else }}
  DATABASE_URL: {{ include "webauthn.databaseUrl" . | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.DATABASE_PASSWORD }}
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | b64enc }}
  {{- end }}
  
  # Redis Configuration
  {{- if .Values.secrets.REDIS_URL }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | b64enc }}
  {{- else }}
  REDIS_URL: {{ include "webauthn.redisUrl" . | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.REDIS_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc }}
  {{- end }}
  
  # Kafka Configuration
  {{- if .Values.secrets.KAFKA_BROKERS }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | b64enc }}
  {{- else }}
  KAFKA_BROKERS: {{ include "webauthn.kafkaBrokers" . | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.KAFKA_USERNAME }}
  KAFKA_USERNAME: {{ .Values.secrets.KAFKA_USERNAME | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.KAFKA_PASSWORD }}
  KAFKA_PASSWORD: {{ .Values.secrets.KAFKA_PASSWORD | b64enc }}
  {{- end }}
  
  # JWT Configuration
  {{- if .Values.secrets.JWT_PRIVATE_KEY }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.JWT_PRIVATE_KEY | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.JWT_PUBLIC_KEY }}
  JWT_PUBLIC_KEY: {{ .Values.secrets.JWT_PUBLIC_KEY | b64enc }}
  {{- end }}
  
  # External Services
  {{- if .Values.secrets.PROMETHEUS_URL }}
  PROMETHEUS_URL: {{ .Values.secrets.PROMETHEUS_URL | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.JAEGER_ENDPOINT }}
  JAEGER_ENDPOINT: {{ .Values.secrets.JAEGER_ENDPOINT | b64enc }}
  {{- end }}