name: INNOVABIZ Enterprise CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-compose-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Valida sintaxe do Compose
        run: docker compose -f docker-compose-enterprise-full.yml config

      - name: Healthcheck automatizado
        run: |
          pwsh ./scripts/healthcheck.ps1
        shell: pwsh

      - name: Salva logs dos serviços críticos
        run: |
          pwsh ./scripts/logs_criticos.ps1
        shell: pwsh

      - name: Salva artefatos de logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-healthcheck
          path: logs/
