name: CI IAM Database

on:
  push:
    paths:
      - 'CoreModules/IAM/database/**'
      - '.github/workflows/ci-iam.yml'
  pull_request:
    paths:
      - 'CoreModules/IAM/database/**'

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: innovabiz_iam
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '15'
          postgresql db: innovabiz_iam
          postgresql user: postgres
          postgresql password: postgres

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install pandas scikit-learn requests

      - name: Esperar o PostgreSQL iniciar
        run: |
          for i in {1..90}; do
            if PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d postgres -c '\q'; then
              echo "PostgreSQL está pronto!"
              break
            else
              echo "Aguardando PostgreSQL iniciar..."
              sleep 3
            fi
          done
      - name: Listar bancos existentes antes do Flyway
        run: |
          echo "Bancos disponíveis no PostgreSQL (porta 5433):"
          PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d postgres -c '\l'
      - name: Contar bases de dados no PostgreSQL
        run: |
          echo "Listando bases de dados no PostgreSQL (porta 5433)..."
          PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d postgres -t -c "SELECT count(*) FROM pg_database WHERE datistemplate = false;" | xargs echo "Total de bases de dados implementadas:"

      - name: Baixar e extrair Flyway CLI
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz | tar xvz
      - name: Rodar scripts de migração (Flyway)
        run: |
          ./flyway-10.11.0/flyway -url=jdbc:postgresql://localhost:5433/innovabiz_iam -user=postgres -password=postgres -locations=filesystem:CoreModules/IAM/database/migrations migrate

      - name: Validar schemas/tabelas principais
        run: |
          psql postgresql://postgres:postgres@localhost:5432/innovabiz_iam -c "\dt iam.*"

      - name: Testar pipeline AI/ML (simulação)
        run: |
          cd CoreModules/IAM/database/scripts/ai_ml
          python test_pipeline.py

      - name: Checar scripts e documentação
        run: |
          ls -l CoreModules/IAM/database/scripts/install/
          cat CoreModules/IAM/database/scripts/install/README.md

      - name: Artefatos de logs e relatórios
        uses: actions/upload-artifact@v4
        with:
          name: iam-anomaly-events
          path: CoreModules/IAM/database/scripts/ai_ml/anomaly_events.csv
